<?php

namespace ContainerJiaaxMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0yRxJV6Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.0yRxJV6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0yRxJV6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MaterielController::delete' => ['privates', '.service_locator.W9kmaFi', 'get_ServiceLocator_W9kmaFiService', true],
            'App\\Controller\\MaterielController::edit' => ['privates', '.service_locator.W9kmaFi', 'get_ServiceLocator_W9kmaFiService', true],
            'App\\Controller\\MaterielController::index' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MaterielController::show' => ['privates', '.service_locator.DLV7SlW', 'get_ServiceLocator_DLV7SlWService', true],
            'App\\Controller\\PretController::delete' => ['privates', '.service_locator.mT006z5', 'get_ServiceLocator_MT006z5Service', true],
            'App\\Controller\\PretController::edit' => ['privates', '.service_locator.mT006z5', 'get_ServiceLocator_MT006z5Service', true],
            'App\\Controller\\PretController::index' => ['privates', '.service_locator.2zY2Mb5', 'get_ServiceLocator_2zY2Mb5Service', true],
            'App\\Controller\\PretController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PretController::show' => ['privates', '.service_locator.0.YQ_d4', 'get_ServiceLocator_0_YQD4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\MaterielController:delete' => ['privates', '.service_locator.W9kmaFi', 'get_ServiceLocator_W9kmaFiService', true],
            'App\\Controller\\MaterielController:edit' => ['privates', '.service_locator.W9kmaFi', 'get_ServiceLocator_W9kmaFiService', true],
            'App\\Controller\\MaterielController:index' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MaterielController:show' => ['privates', '.service_locator.DLV7SlW', 'get_ServiceLocator_DLV7SlWService', true],
            'App\\Controller\\PretController:delete' => ['privates', '.service_locator.mT006z5', 'get_ServiceLocator_MT006z5Service', true],
            'App\\Controller\\PretController:edit' => ['privates', '.service_locator.mT006z5', 'get_ServiceLocator_MT006z5Service', true],
            'App\\Controller\\PretController:index' => ['privates', '.service_locator.2zY2Mb5', 'get_ServiceLocator_2zY2Mb5Service', true],
            'App\\Controller\\PretController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PretController:show' => ['privates', '.service_locator.0.YQ_d4', 'get_ServiceLocator_0_YQD4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\MaterielController::delete' => '?',
            'App\\Controller\\MaterielController::edit' => '?',
            'App\\Controller\\MaterielController::index' => '?',
            'App\\Controller\\MaterielController::new' => '?',
            'App\\Controller\\MaterielController::show' => '?',
            'App\\Controller\\PretController::delete' => '?',
            'App\\Controller\\PretController::edit' => '?',
            'App\\Controller\\PretController::index' => '?',
            'App\\Controller\\PretController::new' => '?',
            'App\\Controller\\PretController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MaterielController:delete' => '?',
            'App\\Controller\\MaterielController:edit' => '?',
            'App\\Controller\\MaterielController:index' => '?',
            'App\\Controller\\MaterielController:new' => '?',
            'App\\Controller\\MaterielController:show' => '?',
            'App\\Controller\\PretController:delete' => '?',
            'App\\Controller\\PretController:edit' => '?',
            'App\\Controller\\PretController:index' => '?',
            'App\\Controller\\PretController:new' => '?',
            'App\\Controller\\PretController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
