<?php

namespace ContainerJiaaxMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPretService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0.YQ_d4.App\Entity\Pret' shared service.
     *
     * @return \App\Entity\Pret
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0.YQ_d4": it references class "App\\Entity\\Pret" but no such service exists.');
    }
}
