<?php

namespace ContainerE3lHSmD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WdczQ9jService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.wdczQ9j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wdczQ9j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailService' => ['privates', 'App\\Service\\MailService', 'getMailServiceService', true],
        ], [
            'entityManager' => '?',
            'mailService' => 'App\\Service\\MailService',
        ]);
    }
}
