<?php

namespace ContainerCp0S5WW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Im7TWv0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Im7TWv0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Im7TWv0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailService' => ['privates', 'App\\Service\\MailService', 'getMailServiceService', true],
            'pret' => ['privates', '.errored..service_locator.Im7TWv0.App\\Entity\\Pret', NULL, 'Cannot autowire service ".service_locator.Im7TWv0": it needs an instance of "App\\Entity\\Pret" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mailService' => 'App\\Service\\MailService',
            'pret' => 'App\\Entity\\Pret',
        ]);
    }
}
