<?php

namespace ContainerEwh0alu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMateriel2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.W9kmaFi.App\Entity\Materiel' shared service.
     *
     * @return \App\Entity\Materiel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.W9kmaFi": it references class "App\\Entity\\Materiel" but no such service exists.');
    }
}
