<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNft41Zx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNft41Zx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNft41Zx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNft41Zx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerNft41Zx\App_KernelProdContainer([
    'container.build_hash' => 'Nft41Zx',
    'container.build_id' => '29c72527',
    'container.build_time' => 1700004806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNft41Zx');
