<?php

namespace ContainerZpni55y;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_DefaultTransportService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'mailer.default_transport' shared service.
     *
     * @return \Symfony\Component\Mailer\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'TransportInterface.php';

        $a = ($container->privates['mailer.transport_factory'] ?? $container->load('getMailer_TransportFactoryService'));

        if (isset($container->privates['mailer.default_transport'])) {
            return $container->privates['mailer.default_transport'];
        }

        return $container->privates['mailer.default_transport'] = $a->fromString($container->getEnv('MAILER_DSN'));
    }
}
