<?php

namespace ContainerZpni55y;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPretService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BxOkYWF.App\Entity\Pret' shared service.
     *
     * @return \App\Entity\Pret
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BxOkYWF": it needs an instance of "App\\Entity\\Pret" but this type has been excluded in "config/services.yaml".');
    }
}
