<?php

namespace ContainerFCee2jU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MaterielRepository' shared autowired service.
     *
     * @return \App\Repository\MaterielRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MaterielRepository'] = new \App\Repository\MaterielRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
