<?php

namespace ContainerFCee2jU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPretTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PretType' shared autowired service.
     *
     * @return \App\Form\PretType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PretType'] = new \App\Form\PretType();
    }
}
