<?php

namespace ContainerLTBEFTz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F6GpbrnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F6Gpbrn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F6Gpbrn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MaterielController::delete' => ['privates', '.service_locator.W9kmaFi', 'get_ServiceLocator_W9kmaFiService', true],
            'App\\Controller\\MaterielController::edit' => ['privates', '.service_locator.W9kmaFi', 'get_ServiceLocator_W9kmaFiService', true],
            'App\\Controller\\MaterielController::index' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MaterielController::show' => ['privates', '.service_locator.DLV7SlW', 'get_ServiceLocator_DLV7SlWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\MaterielController:delete' => ['privates', '.service_locator.W9kmaFi', 'get_ServiceLocator_W9kmaFiService', true],
            'App\\Controller\\MaterielController:edit' => ['privates', '.service_locator.W9kmaFi', 'get_ServiceLocator_W9kmaFiService', true],
            'App\\Controller\\MaterielController:index' => ['privates', '.service_locator.x.XBDpZ', 'get_ServiceLocator_X_XBDpZService', true],
            'App\\Controller\\MaterielController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MaterielController:show' => ['privates', '.service_locator.DLV7SlW', 'get_ServiceLocator_DLV7SlWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\MaterielController::delete' => '?',
            'App\\Controller\\MaterielController::edit' => '?',
            'App\\Controller\\MaterielController::index' => '?',
            'App\\Controller\\MaterielController::new' => '?',
            'App\\Controller\\MaterielController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MaterielController:delete' => '?',
            'App\\Controller\\MaterielController:edit' => '?',
            'App\\Controller\\MaterielController:index' => '?',
            'App\\Controller\\MaterielController:new' => '?',
            'App\\Controller\\MaterielController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
