<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJiaaxMx\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJiaaxMx/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJiaaxMx.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJiaaxMx\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJiaaxMx\App_KernelTestDebugContainer([
    'container.build_hash' => 'JiaaxMx',
    'container.build_id' => 'ae18644b',
    'container.build_time' => 1699564512,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJiaaxMx');
