<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF9IlS6W\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF9IlS6W/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerF9IlS6W.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerF9IlS6W\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerF9IlS6W\App_KernelTestDebugContainer([
    'container.build_hash' => 'F9IlS6W',
    'container.build_id' => '6e1f9d01',
    'container.build_time' => 1699540568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF9IlS6W');
