<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLi8RPNx\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLi8RPNx/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLi8RPNx.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLi8RPNx\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLi8RPNx\App_KernelTestDebugContainer([
    'container.build_hash' => 'Li8RPNx',
    'container.build_id' => '08060c3f',
    'container.build_time' => 1698944759,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLi8RPNx');
