<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_materiel_index' => [[], ['_controller' => 'App\\Controller\\MaterielController::index'], [], [['text', '/materiel/']], [], [], []],
    'app_materiel_new' => [[], ['_controller' => 'App\\Controller\\MaterielController::new'], [], [['text', '/materiel/new']], [], [], []],
    'app_materiel_show' => [['id'], ['_controller' => 'App\\Controller\\MaterielController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/materiel']], [], [], []],
    'app_materiel_edit' => [['id'], ['_controller' => 'App\\Controller\\MaterielController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/materiel']], [], [], []],
    'app_materiel_delete' => [['id'], ['_controller' => 'App\\Controller\\MaterielController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/materiel']], [], [], []],
    'app_pret_index' => [[], ['_controller' => 'App\\Controller\\PretController::index'], [], [['text', '/pret/']], [], [], []],
    'app_pret_new' => [[], ['_controller' => 'App\\Controller\\PretController::new'], [], [['text', '/pret/new']], [], [], []],
    'app_pret_show' => [['id'], ['_controller' => 'App\\Controller\\PretController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pret']], [], [], []],
    'app_pret_edit' => [['id'], ['_controller' => 'App\\Controller\\PretController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/pret']], [], [], []],
    'app_pret_delete' => [['id'], ['_controller' => 'App\\Controller\\PretController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pret']], [], [], []],
];
