<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOW2Wmlx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOW2Wmlx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOW2Wmlx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOW2Wmlx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOW2Wmlx\App_KernelDevDebugContainer([
    'container.build_hash' => 'OW2Wmlx',
    'container.build_id' => '6f388ff2',
    'container.build_time' => 1699612386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOW2Wmlx');
