<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPvZBpTy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPvZBpTy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPvZBpTy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPvZBpTy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPvZBpTy\App_KernelDevDebugContainer([
    'container.build_hash' => 'PvZBpTy',
    'container.build_id' => '714033b6',
    'container.build_time' => 1699544091,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPvZBpTy');
