<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pret extends \App\Entity\Pret implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'materiel_emprunte', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'user_emprunteur', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'date_pret', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'date_rendu_prevue', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'date_rendu_user', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'statut'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'materiel_emprunte', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'user_emprunteur', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'date_pret', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'date_rendu_prevue', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'date_rendu_user', '' . "\0" . 'App\\Entity\\Pret' . "\0" . 'statut'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pret $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMaterielEmprunte(): ?\App\Entity\Materiel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaterielEmprunte', []);

        return parent::getMaterielEmprunte();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaterielEmprunte(?\App\Entity\Materiel $materiel_emprunte): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaterielEmprunte', [$materiel_emprunte]);

        return parent::setMaterielEmprunte($materiel_emprunte);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEmprunteur(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEmprunteur', []);

        return parent::getUserEmprunteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEmprunteur(?\App\Entity\User $user_emprunteur): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEmprunteur', [$user_emprunteur]);

        return parent::setUserEmprunteur($user_emprunteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePret(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePret', []);

        return parent::getDatePret();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePret(\DateTimeInterface $date_pret): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePret', [$date_pret]);

        return parent::setDatePret($date_pret);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRenduPrevue(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRenduPrevue', []);

        return parent::getDateRenduPrevue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRenduPrevue(\DateTimeInterface $date_rendu_prevue): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRenduPrevue', [$date_rendu_prevue]);

        return parent::setDateRenduPrevue($date_rendu_prevue);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRenduUser(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRenduUser', []);

        return parent::getDateRenduUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRenduUser(?\DateTimeInterface $date_rendu_user): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRenduUser', [$date_rendu_user]);

        return parent::setDateRenduUser($date_rendu_user);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(string $statut): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function returnMateriel(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'returnMateriel', []);

        parent::returnMateriel();
    }

}
